services:
  controller.default:
    lazy: true
    class: App\Controller\DefaultController
    arguments: [ "@request", "@templating.twig" ]
  controller.page:
    lazy: true
    class: App\Controller\PageController
    arguments: [ "@request", "@templating.twig", "@repository.page" ]