imports:
  - { resource: 'controllers.yml' }
  - { resource: 'routing.yml' }
  - { resource: 'events.yml' }
  - { resource: 'kernel.yml' }
  - { resource: 'view.yml' }
  - { resource: 'doctrine.yml' }
  - { resource: 'repositories.yml' }